# Basic
title: Brainboys
subtitle: 永远不要放弃自己
welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: 敬畏
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://Brainboys.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: Brainboys
    # duoshuo: 
    
# Social
social:
    weibo: brainboy
    github: Brainboys
    twitter: brainboy
    gplus: 107108267983477358170
    mail: brainboy@foxmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
